# Site settings
title: Working Notes
description: A beautiful, interconnected note-taking system inspired by Andy Matuschak's evergreen notes approach
url: "http://localhost:4000"
baseurl: ""

# Author information
author:
  name: Your Name
  email: your.email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  notes:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
      author: "Your Name"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - serve.py
  - add-note.js
  - package.json
  - admin.html

# Include
include:
  - _notes

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false 