name: Build (manual)

on:
  # Use Vercel's native GitHub integration for deployments.
  # This workflow is kept for optional manual build checks.
  workflow_dispatch:

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: No-op build
        run: |
          echo "Using Vercel native deploys; no GitHub Action deploy."





